### ISSUE TITLE
在HME100K数据集上ExpRate与论文中相差5%

### ISSUE THREAD

**Issue by Howrunz** [LBH1024/CAN#24]
您好，首先感谢您做出了一项很有启发性的工作并开源了代码。

在运行代码过程中我遇到了两个问题，如下：

问题1：在HME100K数据集上，训练90个epoch，测试集的ExpRate最高为53.58，最高点出现于epoch90。之后重新开始，训练240个epoch，测试集的ExpRate最高为62.03，最高点出现于epoch198，与论文中汇报的67.31相差5.28。想问一下是否我在复现哪个环节时没有与您保持一致？如何达到您在论文中汇报的结果？（240个epoch的实验忘了调整`init_epoch`，实际训练了215个epoch）

细节：
1. 我注意到您在[#19](https://github.com/LBH1024/CAN/issues/19)中提供了在HME100K数据集上训练的主要参数，我使用的主要参数如下，其它参数与[config.yaml](https://github.com/LBH1024/CAN/blob/main/config.yaml)一致：
```
seed: 20211024

epochs: 90
batch_size: 8
workers: 8
train_parts: 3
valid_parts: 1
valid_start: 0
save_start: 0

optimizer: Adadelta
lr: 1
lr_decay: cosine
step_ratio: 10
step_decay: 5
eps: 1e-6
weight_decay: 2e-5
beta: 0.9

counting_decoder:
  in_channel: 684
  out_channel: 247
```

2. 训练时未对图片做Resize操作；
3. 训练所使用的GPU为Nvidia Tesla V100 (32GB)，单张。
4. Train loss：
![train_loss](https://user-images.githubusercontent.com/49901071/200111529-b441975e-ea14-493e-8092-e742371a3304.svg)
5. Train ExpRate：
![epoch_train_ExpRate](https://user-images.githubusercontent.com/49901071/200111656-95f9484e-3094-4d0a-bcc5-74d2413d4bff.svg)
6. Eval loss：
![eval_loss](https://user-images.githubusercontent.com/49901071/200111608-d4dbf7ce-6adb-4a7e-9642-6792e50e2a4e.svg)
7. Eval ExpRate：
![epoch_eval_ExpRate](https://user-images.githubusercontent.com/49901071/200111683-7e207eb8-73e9-4649-8195-f8216981b7bc.svg)

问题2：论文中描述HME100K共包含249种符号（包括‘eos’和‘sos’），但我在去重后只得到247种符号（包括‘eos’和‘sos’），不清楚丢失了哪两种。

以上，感谢！
